### PR TITLE
Follow hw keyboard state

### PR DESCRIPTION
**Pull request by pvuorela**
Using contextkit property /maemo/InternalKeyboard/Open, not fully sure if something better should be used instead.

### CODE REVIEW

**Comment by deztructor** [comment]
overall, lgtm. It'd be good to test it (better when statefs use mce as the source of information instead of udev, so (afaik) tohkbd should be supported correctly)

**Comment by kimmoli** [comment]
Not working as expected with tohkbd.
Virtual keyboard is hidden immediately when i attach phone-part, not when keyboard-part is slided out.

Keyboard is preset (AFAIU) when daemon is running, i.e. phone-part of tohkbd is attached. When keyboard is slided out, it emits SW_KEYPAD_SLIDE which should hide/show vkb.

https://github.com/kimmoli/tohkbd2/blob/master/daemon/src/tohkeyboard.cpp#L670

**Comment by deztructor** [comment]
@kimmoli @spiiroin afaik mce should already contain needed changes, so statefs can switch to it?

**Comment by spiiroin** [comment]
@deztructor: yes, mce side slider-kbd signaling should be working

**Comment by deztructor** [comment]
https://github.com/nemomobile/statefs-providers/pull/41

**Comment by deztructor** [comment]
And [corresponding bug](https://bugs.merproject.org/show_bug.cgi?id=1058)

**Comment by kimmoli** [comment]
Tested this with nemomobile/statefs-providers#41 (0.2.74) and observed that after unattaching keyboard the VKB is not show until focused area is touched on screen.
Hiding keyboard works fine, but imo the VKB should automatically reappear when physical keyboard is slided in/removed.

**Comment by pvuorela** [comment]
Switching hw keyboard mode changes plugin and doesn't re-request virtual keyboard. Proper fix would be storing request state in Maliit server, but should get also fixed as side-effect of some day supporting event filtering trough plugin in order to enable composing inputs.

Maybe this would be good enough for starters, though?

**Comment by pvuorela** [comment]
Did also:
https://github.com/maliit/framework/pull/11/files

**Comment by pvuorela** [comment]
Merged vkb reshow upstream and pulled into nemo. Rebased this and added missing context kit BuildRequires. I think all should be now ready to go.

**Pull request merged**
